[onefig]
package_manager = "bun"

[package]
name = "bun"
module = "index.ts"
type = "module"

[package.devDependencies]
"@types/bun" = "latest"

[package.peerDependencies]
typescript = "^5.0.0"

[tsconfig.compilerOptions]
lib = ["ESNext"]
target = "ESNext"
module = "ESNext"
moduleDetection = "force"
jsx = "react-jsx"
allowJs = true
# Bundler mode
moduleResolution = "bundler"
allowImportingTsExtensions = true
verbatimModuleSyntax = true
noEmit = true
# Linting
skipLibCheck = true
strict = true
noFallthroughCasesInSwitch = true
forceConsistentCasingInFileNames = true
